name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  install:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo add-apt-repository universe && sudo apt install python3-proselint
  lint:
    needs: install
    name: lint *.md
    runs-on: ubuntu-latest
    steps:
      - name: proselint md files
        run: proselint *.md
  build:
    needs: lint
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
